// Online-shopping focused mock data — all amounts in INR (₹)

export const MOCK_REQUESTS = [
  {
    id: '1',
    title: 'Apple iPhone 16 Pro — 256GB Natural Titanium',
    amount: 134900,
    category: 'Electronics',
    status: 'pending',
    created_at: '2026-03-28T10:00:00Z',
    description: 'Looking to purchase iPhone 16 Pro 256GB Natural Titanium from Apple India official store.',
    deadline: '2026-04-15',
    product_link: 'https://apple.com/in',
    required_card: 'HDFC Bank',
    is_public: true,
    offer_id: null,
  },
  {
    id: '2',
    title: 'Levi\'s 501 Original Fit Jeans — Dark Stonewash',
    amount: 3999,
    category: 'Fashion & Clothing',
    status: 'matched',
    created_at: '2026-03-25T09:00:00Z',
    description: 'Levi\'s 501 Original Fit Jeans size 32x32 in Dark Stonewash from Myntra.',
    deadline: '2026-04-10',
    product_link: 'https://myntra.com',
    required_card: 'Any',
    is_public: true,
    offer_id: '3',
  },
  {
    id: '3',
    title: 'boAt Airdopes 141 TWS Earbuds',
    amount: 1299,
    category: 'Electronics',
    status: 'completed',
    created_at: '2026-03-20T14:00:00Z',
    description: 'boAt Airdopes 141 Bluetooth TWS earbuds from Amazon India.',
    deadline: '2026-03-28',
    product_link: 'https://amazon.in',
    required_card: 'ICICI Bank',
    is_public: false,
    offer_id: '2',
  },
  {
    id: '4',
    title: 'Mamaearth Vitamin C Face Serum',
    amount: 599,
    category: 'Beauty & Skincare',
    status: 'pending',
    created_at: '2026-03-29T11:00:00Z',
    description: 'Mamaearth Vitamin C Face Serum 30ml from Nykaa.',
    deadline: '2026-04-12',
    product_link: 'https://nykaa.com',
    required_card: 'Any',
    is_public: true,
    offer_id: null,
  },
  {
    id: '5',
    title: 'MacBook Air M3 — 15" Midnight 8GB/256GB',
    amount: 134900,
    category: 'Electronics',
    status: 'pending',
    created_at: '2026-03-30T08:00:00Z',
    description: 'MacBook Air M3 15-inch Midnight from Apple India official online store.',
    deadline: '2026-04-18',
    product_link: 'https://apple.com/in/mac',
    required_card: 'SBI Card',
    is_public: false,
    offer_id: null,
  },
  {
    id: '6',
    title: 'Nike Air Max 270 — Black/White Size 9',
    amount: 12995,
    category: 'Footwear',
    status: 'completed',
    created_at: '2026-03-18T12:00:00Z',
    description: 'Nike Air Max 270 black/white size 9 from Nike India online store.',
    deadline: '2026-03-25',
    product_link: 'https://nike.com',
    required_card: 'Axis Bank',
    is_public: true,
    offer_id: '1',
  },
];

export const MOCK_OFFERS = [
  {
    id: '1',
    card_name: 'HDFC Diners Club Black',
    card_type: 'Diners Club',
    bank: 'HDFC Bank',
    categories: ['Electronics', 'Fashion & Clothing', 'Footwear'],
    discount: 10,
    cashback: 5,
    max_amount: 500000,
    expiry: '2026-04-30',
    status: 'available',
    holder_name: 'Arjun M.',
    deals_done: 18,
    rating: 4.9,
    verified: true,
  },
  {
    id: '2',
    card_name: 'SBI Card PRIME',
    card_type: 'Visa Signature',
    bank: 'SBI Card',
    categories: ['Electronics', 'Beauty & Skincare', 'Health & Wellness'],
    discount: 15,
    cashback: 3,
    max_amount: 100000,
    expiry: '2026-05-15',
    status: 'available',
    holder_name: 'Sneha R.',
    deals_done: 31,
    rating: 5.0,
    verified: true,
  },
  {
    id: '3',
    card_name: 'ICICI Amazon Pay Credit Card',
    card_type: 'Visa',
    bank: 'ICICI Bank',
    categories: ['Fashion & Clothing', 'Groceries', 'Appliances'],
    discount: 12,
    cashback: 5,
    max_amount: 200000,
    expiry: '2026-04-20',
    status: 'available',
    holder_name: 'Rahul K.',
    deals_done: 9,
    rating: 4.7,
    verified: true,
  },
  {
    id: '4',
    card_name: 'Axis Bank Flipkart Card',
    card_type: 'Mastercard',
    bank: 'Axis Bank',
    categories: ['Electronics', 'Mobile & Tablets', 'Accessories'],
    discount: 8,
    cashback: 5,
    max_amount: 150000,
    expiry: '2026-06-30',
    status: 'available',
    holder_name: 'Priya N.',
    deals_done: 5,
    rating: 4.5,
    verified: false,
  },
  {
    id: '5',
    card_name: 'Kotak 811 Dream Different Card',
    card_type: 'Visa',
    bank: 'Kotak Mahindra',
    categories: ['Books & Stationery', 'Toys & Games', 'Home & Kitchen'],
    discount: 7,
    cashback: 2,
    max_amount: 80000,
    expiry: '2026-05-31',
    status: 'available',
    holder_name: 'Vikram T.',
    deals_done: 22,
    rating: 4.8,
    verified: true,
  },
];

export const MOCK_ESCROW = [
  {
    id: 'ESC-001',
    deal_id: 'ESC-001',
    buyer: 'Rohan D.',
    cardholder: 'Sneha R.',
    item: 'SBI Card PRIME — iPhone 16 Pro',
    amount: 134900,
    fee: 2698,
    status: 'held',
    created_at: '2026-03-28T10:00:00Z',
  },
  {
    id: 'ESC-002',
    deal_id: 'ESC-002',
    buyer: 'Meera L.',
    cardholder: 'Rahul K.',
    item: 'ICICI Amazon Pay — Nike Air Max 270',
    amount: 12995,
    fee: 260,
    status: 'releasing',
    created_at: '2026-03-25T09:00:00Z',
  },
  {
    id: 'ESC-003',
    deal_id: 'ESC-003',
    buyer: 'Aditya B.',
    cardholder: 'Arjun M.',
    item: 'HDFC Diners — Levi\'s Jeans',
    amount: 3999,
    fee: 80,
    status: 'released',
    created_at: '2026-03-20T14:00:00Z',
  },
  {
    id: 'ESC-004',
    deal_id: 'ESC-004',
    buyer: 'Aisha P.',
    cardholder: 'Priya N.',
    item: 'Axis Flipkart Card — MacBook Air M3',
    amount: 134900,
    fee: 2698,
    status: 'held',
    created_at: '2026-03-30T08:00:00Z',
  },
];

export const MOCK_DISPUTES = [
  {
    id: 'DIS-001',
    dispute_id: 'DIS-001',
    buyer: 'Rohan D.',
    cardholder: 'Sneha R.',
    item: 'Electronics — boAt Airdopes 141',
    amount: 1299,
    reason: 'Cardholder did not complete the purchase within the agreed timeframe.',
    status: 'open',
    created_at: '2026-03-26T08:00:00Z',
    priority: 'high',
  },
  {
    id: 'DIS-002',
    dispute_id: 'DIS-002',
    buyer: 'Carlos M.',
    cardholder: 'Priya N.',
    item: 'Electronics — MacBook Air M3',
    amount: 134900,
    reason: 'Amount charged was higher than agreed upon in the original request.',
    status: 'investigating',
    created_at: '2026-03-24T14:00:00Z',
    priority: 'medium',
  },
  {
    id: 'DIS-003',
    dispute_id: 'DIS-003',
    buyer: 'Aisha P.',
    cardholder: 'Arjun M.',
    item: 'Footwear — Nike Air Max 270',
    amount: 12995,
    reason: 'Item delivered was a different colour than ordered.',
    status: 'resolved',
    created_at: '2026-03-18T11:00:00Z',
    priority: 'low',
  },
];

export const MOCK_CARDS = [
  {
    id: '1',
    name: 'HDFC Diners Club Black',
    type: 'Diners Club',
    last4: '4521',
    expiry: '09/28',
    bank: 'HDFC Bank',
    gradient: 'from-slate-700 via-slate-800 to-slate-900',
    offers: ['10% off Electronics', '5x reward points on Fashion', '₹500 cashback/month on Online Shopping'],
    active_offers: 2,
    status: 'active',
    earnings: 28400,
  },
  {
    id: '2',
    name: 'SBI Card PRIME',
    type: 'Visa Signature',
    last4: '1009',
    expiry: '03/27',
    bank: 'SBI Card',
    gradient: 'from-blue-700 via-blue-800 to-blue-900',
    offers: ['15% off Electronics', '3% cashback on all Online Shopping', '₹1000 joining bonus'],
    active_offers: 3,
    status: 'active',
    earnings: 74200,
  },
];
